#!/usr/bin/env python3
"""Refresh the generated WaveSpeed model references.

The public catalog is intentionally used here instead of the authenticated
inference catalog. It exposes ranking metadata without requiring a user's API
key, which makes the skill reproducible in CI and for contributors.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.parse import quote, urlencode, urlsplit, urlunsplit
from urllib.request import Request, urlopen


DEFAULT_ENDPOINT = "https://wavespeed.ai/api/models"
DEFAULT_PAGE_SIZE = 48
USER_AGENT = "infs-wavespeed-skill-updater/1.0"


def fetch_catalog(
    endpoint: str, *, sort: str, page: int, page_size: int, timeout: float
) -> dict[str, Any]:
    query = urlencode({"sort": sort, "page": page, "page_size": page_size})
    parsed_endpoint = urlsplit(endpoint)
    url = urlunsplit(
        (parsed_endpoint.scheme, parsed_endpoint.netloc, parsed_endpoint.path, query, "")
    )
    request = Request(url, headers={"Accept": "application/json", "User-Agent": USER_AGENT})

    try:
        with urlopen(request, timeout=timeout) as response:
            raw = response.read()
    except (HTTPError, URLError, TimeoutError) as exc:
        raise RuntimeError(f"failed to fetch {url}: {exc}") from exc

    try:
        payload = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"WaveSpeed returned invalid JSON from {url}") from exc

    if not isinstance(payload, dict) or not isinstance(payload.get("items"), list):
        raise RuntimeError(f"WaveSpeed response from {url} is missing an items array")

    items: list[dict[str, Any]] = []
    for rank, raw_item in enumerate(payload["items"], start=1):
        if not isinstance(raw_item, dict):
            raise RuntimeError(f"WaveSpeed item {rank} is not an object")

        model_id = raw_item.get("model_uuid") or raw_item.get("model_id")
        if not isinstance(model_id, str) or not model_id.strip():
            raise RuntimeError(f"WaveSpeed item {rank} has no model_uuid")

        model_type = raw_item.get("type") or "unknown"
        if not isinstance(model_type, str):
            model_type = str(model_type)

        description = raw_item.get("description") or ""
        if not isinstance(description, str):
            description = str(description)

        items.append(
            {
                "rank": rank,
                "model_id": model_id.strip(),
                "model_name": str(raw_item.get("model_name") or model_id).strip(),
                "type": model_type.strip(),
                "description": " ".join(description.split()),
                "base_price": raw_item.get("base_price"),
                "model_url": model_url(model_id.strip()),
            }
        )

    return {
        "source": url,
        "sort": sort,
        "page": payload.get("page", page),
        "page_size": payload.get("page_size", page_size),
        "total": payload.get("total"),
        "items": items,
    }


def model_url(model_id: str) -> str:
    return f"https://wavespeed.ai/models/{quote(model_id, safe='/')}"


def price_text(value: Any) -> str:
    if value is None or value == "":
        return "—"
    if isinstance(value, float):
        return f"{value:g}"
    return str(value)


def markdown_escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def shorten(value: str, limit: int = 220) -> str:
    if len(value) <= limit:
        return value
    return value[: limit - 1].rstrip() + "…"


def render_reference(title: str, catalog: dict[str, Any]) -> str:
    lines = [
        "<!-- Generated by scripts/update_catalog.py; do not edit by hand. -->",
        f"# {title}",
        "",
        f"Source: `{catalog['source']}`",
        "",
        "This is a ranked snapshot. Ranking, availability, pricing, and model "
        "capabilities can change; inspect the model's current API schema before "
        "running an unfamiliar endpoint.",
        "",
        f"Catalog total at refresh: **{catalog.get('total') or 'unknown'}** models.",
        "",
        "| Rank | Model ID | Type | Base price (catalog units) | What it does |",
        "|---:|---|---|---:|---|",
    ]

    for item in catalog["items"]:
        description = markdown_escape(shorten(item["description"])) or "—"
        model_id = markdown_escape(item["model_id"])
        linked_id = f"[{model_id}]({item['model_url']})"
        lines.append(
            f"| {item['rank']} | {linked_id} | {markdown_escape(item['type'])} | "
            f"{price_text(item['base_price'])} | {description} |"
        )

    lines.extend(
        [
            "",
            "The `base_price` value is copied verbatim from the public catalog. "
            "Use the WaveSpeed playground or pricing endpoint for an exact quote "
            "for a particular input.",
            "",
        ]
    )
    return "\n".join(lines)


def write_atomic(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    with temporary.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    temporary.replace(path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Refresh WaveSpeed popular and newly listed model references."
    )
    parser.add_argument(
        "--endpoint",
        default=DEFAULT_ENDPOINT,
        help=f"Public catalog endpoint (default: {DEFAULT_ENDPOINT})",
    )
    parser.add_argument(
        "--popular-sort",
        default="visits",
        help="Sort value for the popular snapshot (default: visits)",
    )
    parser.add_argument(
        "--new-sort",
        default="created_at",
        help="Sort value for the new snapshot (default: created_at)",
    )
    parser.add_argument("--page", type=int, default=1, help="Catalog page (default: 1)")
    parser.add_argument(
        "--page-size",
        type=int,
        default=DEFAULT_PAGE_SIZE,
        help=f"Models per snapshot (default: {DEFAULT_PAGE_SIZE})",
    )
    parser.add_argument(
        "--timeout", type=float, default=30.0, help="HTTP timeout in seconds (default: 30)"
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Skill directory containing references/ (defaults to this skill)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.page < 1:
        print("--page must be at least 1", file=sys.stderr)
        return 2
    if args.page_size < 1:
        print("--page-size must be at least 1", file=sys.stderr)
        return 2

    try:
        popular = fetch_catalog(
            args.endpoint,
            sort=args.popular_sort,
            page=args.page,
            page_size=args.page_size,
            timeout=args.timeout,
        )
        newest = fetch_catalog(
            args.endpoint,
            sort=args.new_sort,
            page=args.page,
            page_size=args.page_size,
            timeout=args.timeout,
        )
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    output_dir = args.output_dir.resolve()
    references_dir = output_dir / "references"
    catalog = {"popular": popular, "new": newest}

    write_atomic(
        references_dir / "popular-models.md",
        render_reference("WaveSpeed AI popular models", popular),
    )
    write_atomic(
        references_dir / "new-models.md",
        render_reference("WaveSpeed AI newly listed models", newest),
    )
    write_atomic(
        references_dir / "model-catalog.json",
        json.dumps(catalog, ensure_ascii=False, indent=2) + "\n",
    )

    print(
        f"Updated {references_dir / 'popular-models.md'} "
        f"({len(popular['items'])} models; sort={popular['sort']})"
    )
    print(
        f"Updated {references_dir / 'new-models.md'} "
        f"({len(newest['items'])} models; sort={newest['sort']})"
    )
    print(f"Updated {references_dir / 'model-catalog.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
